# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog:
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 693)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 650, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 40, 281, 71))
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 110, 281, 71))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 90, 221, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 281, 71))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 250, 281, 71))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 320, 281, 71))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 390, 281, 71))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 460, 281, 71))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 160, 221, 41))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 300, 221, 41))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 370, 221, 41))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 230, 221, 41))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 440, 221, 41))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setObjectName("pushButton_13")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Button, QtGui.QColor(QtCore.Qt.black))

        dialog_palette = QtGui.QPalette()
        dialog_palette.setColor(QtGui.QPalette.Window, QtGui.QColor(QtCore.Qt.cyan))
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Musical Ladder Demo"))

        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_1.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_1.update()

        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_2.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_2.update()

        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_3.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                        'color: black;')
        self.pushButton_3.update()

        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_4.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_4.update()

        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_5.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_5.update()

        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_6.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_6.update()

        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_7.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_7.update()

        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_8.setStyleSheet('background-color: #ffffff; border: 1px solid black;border-radius: 5px; '
                                        'color: white;')
        self.pushButton_8.update()

        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_9.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                        'color: black;')
        self.pushButton_9.update()

        self.pushButton_10.setText(_translate("Dialog", "10"))
        self.pushButton_10.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                         'color: black;')
        self.pushButton_10.update()

        self.pushButton_11.setText(_translate("Dialog", "11"))
        self.pushButton_11.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                         'color: black;')
        self.pushButton_11.update()

        self.pushButton_12.setText(_translate("Dialog", "12"))
        self.pushButton_12.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                         'selection-color: yellow; color: black;')
        self.pushButton_12.update()

        self.pushButton_13.setText(_translate("Dialog", "13"))
        self.pushButton_13.setStyleSheet('background-color: #000000; border: 1px solid black;border-radius: 5px; '
                                         'color: black;')
        self.pushButton_13.update()

